"""create catalogue core

Revision ID: ec835a0ae308
Revises:
Create Date: 2026-07-26 16:03:07.581143

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec835a0ae308"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_countries_code"), "countries", ["code"], unique=True)
    op.create_table(
        "manufacturers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manufacturers_country_id"), "manufacturers", ["country_id"], unique=False
    )
    op.create_index(
        op.f("ix_manufacturers_is_active"), "manufacturers", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_manufacturers_name"), "manufacturers", ["name"], unique=False)
    op.create_index(op.f("ix_manufacturers_slug"), "manufacturers", ["slug"], unique=True)
    op.create_table(
        "parks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=True),
        sa.Column("city", sa.String(length=160), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parks_country_id"), "parks", ["country_id"], unique=False)
    op.create_index(op.f("ix_parks_is_active"), "parks", ["is_active"], unique=False)
    op.create_index(op.f("ix_parks_name"), "parks", ["name"], unique=False)
    op.create_index("ix_parks_name_country", "parks", ["name", "country_id"], unique=False)
    op.create_index(op.f("ix_parks_slug"), "parks", ["slug"], unique=True)
    op.create_table(
        "coasters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("park_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "operating",
                "under_construction",
                "standing_not_operating",
                "closed",
                "removed",
                "unknown",
                name="coasterstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("height_m", sa.Float(), nullable=True),
        sa.Column("speed_kmh", sa.Float(), nullable=True),
        sa.Column("length_m", sa.Float(), nullable=True),
        sa.Column("drop_m", sa.Float(), nullable=True),
        sa.Column("inversions", sa.Integer(), nullable=True),
        sa.Column("capacity_pph", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["manufacturer_id"], ["manufacturers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["park_id"], ["parks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("park_id", "slug", name="uq_coasters_park_slug"),
    )
    op.create_index(op.f("ix_coasters_is_active"), "coasters", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_coasters_manufacturer_id"), "coasters", ["manufacturer_id"], unique=False
    )
    op.create_index(op.f("ix_coasters_name"), "coasters", ["name"], unique=False)
    op.create_index("ix_coasters_name_park", "coasters", ["name", "park_id"], unique=False)
    op.create_index(op.f("ix_coasters_park_id"), "coasters", ["park_id"], unique=False)
    op.create_index(op.f("ix_coasters_slug"), "coasters", ["slug"], unique=False)
    op.create_index(op.f("ix_coasters_status"), "coasters", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coasters_status"), table_name="coasters")
    op.drop_index(op.f("ix_coasters_slug"), table_name="coasters")
    op.drop_index(op.f("ix_coasters_park_id"), table_name="coasters")
    op.drop_index("ix_coasters_name_park", table_name="coasters")
    op.drop_index(op.f("ix_coasters_name"), table_name="coasters")
    op.drop_index(op.f("ix_coasters_manufacturer_id"), table_name="coasters")
    op.drop_index(op.f("ix_coasters_is_active"), table_name="coasters")
    op.drop_table("coasters")
    op.drop_index(op.f("ix_parks_slug"), table_name="parks")
    op.drop_index("ix_parks_name_country", table_name="parks")
    op.drop_index(op.f("ix_parks_name"), table_name="parks")
    op.drop_index(op.f("ix_parks_is_active"), table_name="parks")
    op.drop_index(op.f("ix_parks_country_id"), table_name="parks")
    op.drop_table("parks")
    op.drop_index(op.f("ix_manufacturers_slug"), table_name="manufacturers")
    op.drop_index(op.f("ix_manufacturers_name"), table_name="manufacturers")
    op.drop_index(op.f("ix_manufacturers_is_active"), table_name="manufacturers")
    op.drop_index(op.f("ix_manufacturers_country_id"), table_name="manufacturers")
    op.drop_table("manufacturers")
    op.drop_index(op.f("ix_countries_code"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
